#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'
module Predicator
  class GeneratedParser < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
    10,    21,    22,     8,     9,    15,    16,    17,    18,    19,
    47,    10,     6,    37,     8,     9,    15,    16,    17,    18,
    19,    10,    34,     6,     8,     9,    15,    16,    17,    18,
    19,    10,    48,     6,     8,     9,    15,    16,    17,    18,
    19,    10,    33,     6,     8,     9,    15,    16,    17,    18,
    19,    24,    31,     6,   nil,    25,    30,    29,    28,    27,
    26,    15,    16,    17,    18,    19,    15,    16,    17,    18,
    19,    20,    45,    46,    21,    22,    15,    16,    17,    18,
    19,    15,    16,    17,    18,    19,    15,    16,    17,    18,
    19,    15,    16,    17,    18,    19,    15,    16,    17,    18,
    19,    15,    16,    17,    18,    19 ]

racc_action_check = [
     0,    23,    23,     0,     0,     0,     0,     0,     0,     0,
    33,     6,     0,    23,     6,     6,     6,     6,     6,     6,
     6,    22,    20,     6,    22,    22,    22,    22,    22,    22,
    22,    10,    38,    22,    10,    10,    10,    10,    10,    10,
    10,    21,    19,    10,    21,    21,    21,    21,    21,    21,
    21,     7,     7,    21,   nil,     7,     7,     7,     7,     7,
     7,    24,    24,    24,    24,    24,    48,    48,    48,    48,
    48,     1,    31,    31,     1,     1,    30,    30,    30,    30,
    30,    25,    25,    25,    25,    25,    26,    26,    26,    26,
    26,    27,    27,    27,    27,    27,    29,    29,    29,    29,
    29,    28,    28,    28,    28,    28 ]

racc_action_pointer = [
    -2,    71,   nil,   nil,   nil,   nil,     9,    39,   nil,   nil,
    29,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    29,
    22,    39,    19,    -2,    54,    74,    79,    84,    94,    89,
    69,    50,   nil,    -1,   nil,   nil,   nil,   nil,    29,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    59,   nil ]

racc_action_default = [
   -29,   -29,    -1,    -2,    -3,    -4,   -29,   -29,    -7,    -8,
   -29,   -20,   -21,   -22,   -23,   -24,   -25,   -26,   -27,   -29,
   -29,   -29,   -29,   -29,   -29,   -29,   -29,   -29,   -29,   -29,
   -29,   -29,   -11,   -29,    50,    -9,   -10,    -5,   -29,   -12,
   -13,   -14,   -15,   -16,   -17,   -18,   -19,   -28,   -29,    -6 ]

racc_goto_table = [
    38,    39,    40,    41,    42,    43,    44,     1,   nil,   nil,
   nil,   nil,   nil,    23,   nil,   nil,   nil,    32,   nil,   nil,
   nil,   nil,   nil,   nil,    49,   nil,   nil,   nil,    35,    36 ]

racc_goto_check = [
     6,     6,     6,     6,     6,     6,     6,     1,   nil,   nil,
   nil,   nil,   nil,     1,   nil,   nil,   nil,     1,   nil,   nil,
   nil,   nil,   nil,   nil,     6,   nil,   nil,   nil,     1,     1 ]

racc_goto_pointer = [
   nil,     7,   nil,   nil,   nil,   nil,   -24,   nil,   nil,   nil,
   nil ]

racc_goto_default = [
   nil,   nil,     2,     3,     4,     5,     7,    11,    12,    13,
    14 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 25, :_reduce_none,
  1, 25, :_reduce_none,
  1, 25, :_reduce_none,
  1, 25, :_reduce_none,
  3, 25, :_reduce_5,
  5, 25, :_reduce_6,
  1, 26, :_reduce_7,
  1, 26, :_reduce_8,
  3, 27, :_reduce_9,
  3, 27, :_reduce_10,
  2, 27, :_reduce_11,
  3, 28, :_reduce_12,
  3, 28, :_reduce_13,
  3, 28, :_reduce_14,
  3, 28, :_reduce_15,
  3, 28, :_reduce_16,
  3, 28, :_reduce_17,
  3, 29, :_reduce_18,
  3, 29, :_reduce_19,
  1, 30, :_reduce_none,
  1, 30, :_reduce_none,
  1, 31, :_reduce_none,
  1, 31, :_reduce_none,
  1, 33, :_reduce_24,
  1, 34, :_reduce_25,
  1, 34, :_reduce_26,
  1, 34, :_reduce_27,
  3, 32, :_reduce_28 ]

racc_reduce_n = 29

racc_shift_n = 50

racc_token_table = {
  false => 0,
  :error => 1,
  :tBANG => 2,
  :tAND => 3,
  :tOR => 4,
  :tTRUE => 5,
  :tFALSE => 6,
  :tSTRING => 7,
  :tFLOAT => 8,
  :tINTEGER => 9,
  :tDATE => 10,
  :tIDENTIFIER => 11,
  :tBETWEEN => 12,
  :tDOT => 13,
  :tLPAREN => 14,
  :tRPAREN => 15,
  :tEQ => 16,
  :tNEQ => 17,
  :tLEQ => 18,
  :tGEQ => 19,
  :tLT => 20,
  :tGT => 21,
  :tBLANK => 22,
  :tPRESENT => 23 }

racc_nt_base = 24

racc_use_result_var = false

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "tBANG",
  "tAND",
  "tOR",
  "tTRUE",
  "tFALSE",
  "tSTRING",
  "tFLOAT",
  "tINTEGER",
  "tDATE",
  "tIDENTIFIER",
  "tBETWEEN",
  "tDOT",
  "tLPAREN",
  "tRPAREN",
  "tEQ",
  "tNEQ",
  "tLEQ",
  "tGEQ",
  "tLT",
  "tGT",
  "tBLANK",
  "tPRESENT",
  "$start",
  "predicate",
  "boolean_predicate",
  "logical_predicate",
  "relation_predicate",
  "method_predicate",
  "value",
  "scalar",
  "variable",
  "string",
  "literal" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

module_eval(<<'.,.,', 'parser.y', 14)
  def _reduce_5(val, _values)
     val[1] 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 15)
  def _reduce_6(val, _values)
     Predicator::Predicates::Between.new val[0], val[2], val[4] 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 18)
  def _reduce_7(val, _values)
     Predicator::Predicates::True.new 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 19)
  def _reduce_8(val, _values)
     Predicator::Predicates::False.new 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 22)
  def _reduce_9(val, _values)
     Predicator::Predicates::And.new [val[0], val[2]] 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 23)
  def _reduce_10(val, _values)
     Predicator::Predicates::Or.new [val[0], val[2]] 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 24)
  def _reduce_11(val, _values)
     Predicator::Predicates::Not.new val[0] 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 27)
  def _reduce_12(val, _values)
     Predicator::Predicates::Equal.new val[0], val[2] 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 28)
  def _reduce_13(val, _values)
     Predicator::Predicates::GreaterThan.new val[0], val[2] 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 29)
  def _reduce_14(val, _values)
     Predicator::Predicates::LessThan.new val[0], val[2] 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 30)
  def _reduce_15(val, _values)
     Predicator::Predicates::GreaterThanOrEqual.new val[0], val[2] 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 31)
  def _reduce_16(val, _values)
     Predicator::Predicates::LessThanOrEqual.new val[0], val[2] 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 32)
  def _reduce_17(val, _values)
     Predicator::Predicates::NotEqual.new val[0], val[2] 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 35)
  def _reduce_18(val, _values)
     Predicator::Predicates::Method.new val[0], val[2] 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 36)
  def _reduce_19(val, _values)
     Predicator::Predicates::Method.new val[0], val[2] 
  end
.,.,

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

# reduce 23 omitted

module_eval(<<'.,.,', 'parser.y', 47)
  def _reduce_24(val, _values)
     val[0] 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 50)
  def _reduce_25(val, _values)
     val[0].to_f 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 51)
  def _reduce_26(val, _values)
     val[0].to_i 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 52)
  def _reduce_27(val, _values)
     Date.new *val[0] 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 55)
  def _reduce_28(val, _values)
     Predicator::Variable.new val[0], val[2] 
  end
.,.,

def _reduce_none(val, _values)
  val[0]
end

  end   # class GeneratedParser
  end   # module Predicator
