#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'

require "predicator/lexer"
require "predicator/visitors"
require "predicator/ast"
module Predicator
  class Parser < Racc::Parser

    def initialize
      @lexer = Lexer.new
    end

    def parse string
      @lexer.scan_setup string
      do_parse
    end

    def next_token
      @lexer.next_token
    end

    def on_error type, val, values
      super
    rescue Racc::ParseError
      trace = values.each_with_index.map{|l, i| "#{' ' * i}#{l}"}
      raise ParseError, "\nparse error on value #{val.inspect}\n#{trace.join("\n")}"
    end

##### State transition tables begin ###

racc_action_table = [
     7,     8,    10,    31,     9,    12,    21,    22,    25,    26,
    18,    17,    19,     7,     8,    10,    27,     9,    12,    18,
    17,    19,    28,    18,    17,    19,     7,     8,    10,   nil,
     9,    12,    18,    17,    19,   nil,    18,    17,    19,     7,
     8,    10,   nil,     9,    12,    21,    22,    21,    22,    18,
    17,    19,     7,     8,    10,   nil,     9,    12,    20,    21,
    22,   nil,    18,    17,    19,   nil,    21,    22 ]

racc_action_check = [
     0,     0,     0,    24,     0,     0,    24,    24,    11,    11,
     0,     0,     0,     9,     9,     9,    12,     9,     9,    25,
    25,    25,    20,     9,     9,     9,    10,    10,    10,   nil,
    10,    10,    26,    26,    26,   nil,    10,    10,    10,    21,
    21,    21,   nil,    21,    21,    23,    23,    29,    29,    21,
    21,    21,    22,    22,    22,   nil,    22,    22,     1,    30,
    30,   nil,    22,    22,    22,   nil,     1,     1 ]

racc_action_pointer = [
    -2,    58,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    11,
    24,    -2,     2,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    22,    37,    50,    37,    -2,     7,    20,   nil,   nil,    39,
    51,   nil,   nil,   nil ]

racc_action_default = [
   -20,   -23,    -1,    -2,    -3,    -4,    -5,    -6,    -7,   -20,
   -20,   -23,   -23,   -15,   -16,   -17,   -18,   -19,   -21,   -22,
   -23,   -20,   -20,    -8,   -23,   -20,   -20,   -14,    34,    -9,
   -10,   -11,   -12,   -13 ]

racc_goto_table = [
     1,    32,    33,   nil,   nil,   nil,   nil,   nil,   nil,    23,
    24,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    29,    30 ]

racc_goto_check = [
     1,     7,     7,   nil,   nil,   nil,   nil,   nil,   nil,     1,
     1,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     1,     1 ]

racc_goto_pointer = [
   nil,     0,   nil,   nil,   nil,   nil,   nil,   -24,   nil,   nil,
   nil,   nil ]

racc_goto_default = [
   nil,   nil,     2,     3,     4,     5,     6,    11,    13,    14,
    15,    16 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 16, :_reduce_none,
  1, 16, :_reduce_none,
  1, 16, :_reduce_none,
  1, 16, :_reduce_none,
  1, 16, :_reduce_none,
  1, 17, :_reduce_6,
  1, 17, :_reduce_7,
  2, 18, :_reduce_8,
  3, 18, :_reduce_9,
  3, 18, :_reduce_10,
  3, 19, :_reduce_11,
  3, 20, :_reduce_12,
  3, 20, :_reduce_13,
  2, 21, :_reduce_14,
  1, 22, :_reduce_none,
  1, 22, :_reduce_none,
  1, 23, :_reduce_none,
  1, 23, :_reduce_none,
  1, 25, :_reduce_19,
  0, 26, :_reduce_none,
  1, 26, :_reduce_21,
  1, 24, :_reduce_22 ]

racc_reduce_n = 23

racc_shift_n = 34

racc_token_table = {
  false => 0,
  :error => 1,
  :TRUE => 2,
  :FALSE => 3,
  :LPAREN => 4,
  :RPAREN => 5,
  :BANG => 6,
  :AT => 7,
  :AND => 8,
  :OR => 9,
  :EQ => 10,
  :GT => 11,
  :INTEGER => 12,
  :STRING => 13,
  :IDENTIFIER => 14 }

racc_nt_base = 15

racc_use_result_var = false

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "TRUE",
  "FALSE",
  "LPAREN",
  "RPAREN",
  "BANG",
  "AT",
  "AND",
  "OR",
  "EQ",
  "GT",
  "INTEGER",
  "STRING",
  "IDENTIFIER",
  "$start",
  "predicate",
  "boolean_predicate",
  "logical_predicate",
  "group_predicate",
  "comparison_predicate",
  "named_predicate",
  "value",
  "scalar",
  "variable",
  "string",
  "literal" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

def _reduce_6(val, _values)
 AST::True.new true 
end

def _reduce_7(val, _values)
 AST::False.new false 
end

def _reduce_8(val, _values)
 AST::Not.new val.last 
end

def _reduce_9(val, _values)
 AST::And.new val.first, val.last 
end

def _reduce_10(val, _values)
 AST::Or.new val.first, val.last 
end

def _reduce_11(val, _values)
 AST::Group.new val[1] 
end

def _reduce_12(val, _values)
 AST::Equal.new val.first, val.last 
end

def _reduce_13(val, _values)
 AST::GreaterThan.new val.first, val.last 
end

def _reduce_14(val, _values)
 AST::Named.new val.last 
end

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

def _reduce_19(val, _values)
 AST::String.new val.first 
end

# reduce 20 omitted

def _reduce_21(val, _values)
 AST::Integer.new val.first.to_i 
end

def _reduce_22(val, _values)
 AST::Variable.new val.first 
end

def _reduce_none(val, _values)
  val[0]
end

  end   # class Parser
  end   # module Predicator
