#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'

require "predicator/lexer.rex"
require "predicator/visitors"
require "predicator/ast"
module Predicator
  class Parser < Racc::Parser

    def initialize
      @lexer = Lexer.new
    end

    def parse string
      @lexer.parse string
      do_parse
    end

    def next_token
      @lexer.next_token
    end

    def on_error type, val, values
      super
    rescue Racc::ParseError
      trace = values.each_with_index.map{|l, i| "#{' ' * i}#{l}"}
      raise ParseError, "\nparse error on value #{val.inspect}\n#{trace.join("\n")}"
    end

##### State transition tables begin ###

racc_action_table = [
     6,     7,     9,     6,     7,     9,     8,    14,    13,     8,
     6,     7,     9,    45,    17,    18,     8,    46,    14,    13,
    15,    14,    13,    15,    37,     6,     7,     9,    14,    13,
    15,     8,     6,     7,     9,    16,    17,    18,     8,    14,
    13,    15,    27,    14,    13,    15,    28,    26,    17,    18,
    14,    13,    15,    21,    22,    23,    24,    25,    31,    14,
    13,    15,    14,    13,    15,    37,    17,    18,    14,    13,
    15,    14,    13,    15,    14,    13,    17,    18,    38,    39,
    40 ]

racc_action_check = [
     0,     0,     0,     8,     8,     8,     0,    37,    37,     8,
     9,     9,     9,    41,    19,    19,     9,    41,     0,     0,
     0,     8,     8,     8,    38,    18,    18,    18,     9,     9,
     9,    18,    17,    17,    17,     1,    30,    30,    17,    23,
    23,    23,    12,    18,    18,    18,    16,    10,     1,     1,
    17,    17,    17,    10,    10,    10,    10,    10,    20,    21,
    21,    21,    22,    22,    22,    25,    20,    20,    24,    24,
    24,    40,    40,    40,    46,    46,    29,    29,    26,    27,
    35 ]

racc_action_pointer = [
    -2,    35,   nil,   nil,   nil,   nil,   nil,   nil,     1,     8,
    38,   nil,    32,   nil,   nil,   nil,    46,    30,    23,     1,
    53,    39,    42,    19,    48,    59,    59,    57,   nil,    63,
    23,   nil,   nil,   nil,   nil,    67,   nil,   -13,    18,   nil,
    51,     6,   nil,   nil,   nil,   nil,    54,   nil ]

racc_action_default = [
   -26,   -26,    -1,    -2,    -3,    -4,    -5,    -6,   -26,   -26,
   -26,   -20,   -21,   -22,   -23,   -24,   -26,   -26,   -26,    -7,
   -26,   -26,   -26,   -26,   -26,   -26,   -26,   -26,    48,    -8,
    -9,   -10,   -11,   -12,   -13,   -26,   -15,   -26,   -26,   -25,
   -26,   -26,   -18,   -16,   -14,   -17,   -26,   -19 ]

racc_goto_table = [
    32,    33,    34,    35,     1,    36,    42,    41,   nil,   nil,
   nil,   nil,    19,    20,   nil,    47,   nil,   nil,    43,    44,
   nil,    29,    30 ]

racc_goto_check = [
     6,     6,     6,     6,     1,     7,     9,     8,   nil,   nil,
   nil,   nil,     1,     1,   nil,     9,   nil,   nil,     7,     6,
   nil,     1,     1 ]

racc_goto_pointer = [
   nil,     4,   nil,   nil,   nil,   nil,   -21,   -20,   -30,   -31,
   nil ]

racc_goto_default = [
   nil,   nil,     2,     3,     4,     5,    10,   nil,   nil,    11,
    12 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 24, :_reduce_none,
  1, 24, :_reduce_none,
  1, 24, :_reduce_none,
  1, 24, :_reduce_none,
  1, 25, :_reduce_5,
  1, 25, :_reduce_6,
  2, 26, :_reduce_7,
  3, 26, :_reduce_8,
  3, 26, :_reduce_9,
  3, 27, :_reduce_10,
  3, 28, :_reduce_11,
  3, 28, :_reduce_12,
  3, 28, :_reduce_13,
  5, 28, :_reduce_14,
  3, 28, :_reduce_15,
  4, 28, :_reduce_16,
  3, 30, :_reduce_17,
  1, 31, :_reduce_18,
  3, 31, :_reduce_19,
  1, 29, :_reduce_none,
  1, 29, :_reduce_none,
  1, 32, :_reduce_22,
  1, 32, :_reduce_23,
  1, 33, :_reduce_24,
  3, 33, :_reduce_25 ]

racc_reduce_n = 26

racc_shift_n = 48

racc_token_table = {
  false => 0,
  :error => 1,
  :TRUE => 2,
  :FALSE => 3,
  :LPAREN => 4,
  :RPAREN => 5,
  :LBRACKET => 6,
  :RBRACKET => 7,
  :BANG => 8,
  :NOT => 9,
  :DOT => 10,
  :COMMA => 11,
  :AT => 12,
  :AND => 13,
  :OR => 14,
  :EQ => 15,
  :GT => 16,
  :LT => 17,
  :BETWEEN => 18,
  :IN => 19,
  :INTEGER => 20,
  :STRING => 21,
  :IDENTIFIER => 22 }

racc_nt_base = 23

racc_use_result_var = false

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "TRUE",
  "FALSE",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "BANG",
  "NOT",
  "DOT",
  "COMMA",
  "AT",
  "AND",
  "OR",
  "EQ",
  "GT",
  "LT",
  "BETWEEN",
  "IN",
  "INTEGER",
  "STRING",
  "IDENTIFIER",
  "$start",
  "predicate",
  "boolean_predicate",
  "logical_predicate",
  "group_predicate",
  "comparison_predicate",
  "value",
  "array",
  "array_contents",
  "literal",
  "variable" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

def _reduce_5(val, _values)
 AST::True.new true 
end

def _reduce_6(val, _values)
 AST::False.new false 
end

def _reduce_7(val, _values)
 AST::Not.new val.last 
end

def _reduce_8(val, _values)
 AST::And.new val.first, val.last 
end

def _reduce_9(val, _values)
 AST::Or.new val.first, val.last 
end

def _reduce_10(val, _values)
 AST::Group.new val[1] 
end

def _reduce_11(val, _values)
 AST::Equal.new val.first, val.last 
end

def _reduce_12(val, _values)
 AST::GreaterThan.new val.first, val.last 
end

def _reduce_13(val, _values)
 AST::LessThan.new val.first, val.last 
end

def _reduce_14(val, _values)
 AST::Between.new val.first, val[2], val.last 
end

def _reduce_15(val, _values)
 AST::In.new val.first, val.last
end

def _reduce_16(val, _values)
 AST::NotIn.new val.first, val.last
end

def _reduce_17(val, _values)
AST::Array.new val[1]
end

def _reduce_18(val, _values)
[val.first]
end

def _reduce_19(val, _values)
[val.first, val.last].flatten
end

# reduce 20 omitted

# reduce 21 omitted

def _reduce_22(val, _values)
 AST::String.new val.first 
end

def _reduce_23(val, _values)
 AST::Integer.new val.first.to_i 
end

def _reduce_24(val, _values)
 AST::Variable.new val.first 
end

def _reduce_25(val, _values)
 AST::Variable.new [val.first, val.last].flatten.join(".") 
end

def _reduce_none(val, _values)
  val[0]
end

  end   # class Parser
  end   # module Predicator
