#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'

require "predicator/lexer.rex"
require "predicator/visitors"
require "predicator/ast"
module Predicator
  class Parser < Racc::Parser

    def initialize
      @lexer = Lexer.new
    end

    def parse string
      @lexer.parse string
      do_parse
    end

    def next_token
      @lexer.next_token
    end

    def on_error type, val, values
      super
    rescue Racc::ParseError
      trace = values.each_with_index.map{|l, i| "#{' ' * i}#{l}"}
      raise ParseError, "\nparse error on value #{val.inspect}\n#{trace.join("\n")}"
    end

##### State transition tables begin ###

racc_action_table = [
     6,     7,    10,     6,     7,    10,     9,    32,    14,     9,
     6,     7,    10,     6,     7,    10,     9,    31,    32,     9,
    13,    15,    16,    13,    26,     6,     7,    10,    22,    23,
    13,     9,    43,    13,    17,    18,    19,    20,    21,    52,
    15,    16,    54,    53,    31,    13,    55,    15,    16,    31,
    32,    31,    32,    15,    16,    31,    32,    15,    16,    40,
    41,    42,    44,    40,    31,    31 ]

racc_action_check = [
    15,    15,    15,     9,     9,     9,    15,    55,     1,     9,
    10,    10,    10,    16,    16,    16,    10,    18,    18,    16,
    15,     1,     1,     9,    14,     0,     0,     0,     8,     8,
    10,     0,    25,    16,     8,     8,     8,     8,     8,    45,
    25,    25,    47,    45,    20,     0,    47,    28,    28,    40,
    40,    17,    17,    27,    27,    19,    19,    24,    24,    21,
    22,    23,    37,    41,    44,    53 ]

racc_action_pointer = [
    23,     8,   nil,   nil,   nil,   nil,   nil,   nil,    19,     1,
     8,   nil,   nil,   nil,    24,    -2,    11,    31,    -3,    35,
    24,    53,    41,    39,    44,    27,   nil,    40,    34,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    49,   nil,   nil,
    29,    57,   nil,   nil,    44,    32,   nil,    35,   nil,   nil,
   nil,   nil,   nil,    45,   nil,   -14,   nil,   nil ]

racc_action_default = [
   -35,   -35,    -1,    -2,    -3,    -4,    -5,    -6,    -7,   -35,
   -35,   -12,   -13,   -33,   -35,   -35,   -35,   -35,   -35,   -35,
   -35,   -35,   -35,   -35,    -8,   -35,    58,    -9,   -10,   -14,
   -20,   -31,   -32,   -15,   -21,   -16,   -22,   -35,   -18,   -23,
   -35,   -35,   -34,   -11,   -35,   -35,   -26,   -35,   -29,   -19,
   -24,   -17,   -25,   -35,   -28,   -35,   -27,   -30 ]

racc_goto_table = [
    30,    34,    36,    29,    33,    35,    37,    38,    39,     1,
    45,    47,   nil,   nil,   nil,   nil,   nil,   nil,    24,    25,
   nil,   nil,   nil,    48,    27,    28,    46,    49,    50,   nil,
    51,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    57,    56 ]

racc_goto_check = [
    11,    11,    11,     9,     9,     9,     9,    10,    12,     1,
    13,    14,   nil,   nil,   nil,   nil,   nil,   nil,     1,     1,
   nil,   nil,   nil,    11,     1,     1,     9,    10,    12,   nil,
     9,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    11,     9 ]

racc_goto_pointer = [
   nil,     9,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   -14,
   -14,   -17,   -13,   -30,   -29 ]

racc_goto_default = [
   nil,   nil,     2,     3,     4,     5,     8,    11,    12,   nil,
   nil,   nil,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 24, :_reduce_none,
  1, 24, :_reduce_none,
  1, 24, :_reduce_none,
  1, 24, :_reduce_none,
  1, 25, :_reduce_5,
  1, 25, :_reduce_6,
  1, 25, :_reduce_7,
  2, 26, :_reduce_8,
  3, 26, :_reduce_9,
  3, 26, :_reduce_10,
  3, 27, :_reduce_11,
  1, 28, :_reduce_none,
  1, 28, :_reduce_none,
  3, 30, :_reduce_14,
  3, 30, :_reduce_15,
  3, 30, :_reduce_16,
  5, 30, :_reduce_17,
  3, 30, :_reduce_18,
  4, 30, :_reduce_19,
  3, 31, :_reduce_20,
  3, 31, :_reduce_21,
  3, 31, :_reduce_22,
  3, 31, :_reduce_23,
  4, 31, :_reduce_24,
  3, 33, :_reduce_25,
  1, 36, :_reduce_none,
  3, 36, :_reduce_27,
  3, 35, :_reduce_28,
  1, 37, :_reduce_none,
  3, 37, :_reduce_30,
  1, 32, :_reduce_31,
  1, 34, :_reduce_32,
  1, 29, :_reduce_33,
  3, 29, :_reduce_34 ]

racc_reduce_n = 35

racc_shift_n = 58

racc_token_table = {
  false => 0,
  :error => 1,
  :TRUE => 2,
  :FALSE => 3,
  :LPAREN => 4,
  :RPAREN => 5,
  :LBRACKET => 6,
  :RBRACKET => 7,
  :BANG => 8,
  :NOT => 9,
  :DOT => 10,
  :COMMA => 11,
  :AT => 12,
  :AND => 13,
  :OR => 14,
  :EQ => 15,
  :GT => 16,
  :LT => 17,
  :BETWEEN => 18,
  :IN => 19,
  :INTEGER => 20,
  :STRING => 21,
  :IDENTIFIER => 22 }

racc_nt_base = 23

racc_use_result_var = false

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "TRUE",
  "FALSE",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "BANG",
  "NOT",
  "DOT",
  "COMMA",
  "AT",
  "AND",
  "OR",
  "EQ",
  "GT",
  "LT",
  "BETWEEN",
  "IN",
  "INTEGER",
  "STRING",
  "IDENTIFIER",
  "$start",
  "predicate",
  "boolean_predicate",
  "logical_predicate",
  "group_predicate",
  "comparison_predicate",
  "variable",
  "integer_comparison_predicate",
  "string_comparison_predicate",
  "integer",
  "integer_array",
  "string",
  "string_array",
  "integer_array_contents",
  "string_array_contents" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

def _reduce_5(val, _values)
 AST::True.new true 
end

def _reduce_6(val, _values)
 AST::False.new false 
end

def _reduce_7(val, _values)
 AST::BooleanVariable.new val.first 
end

def _reduce_8(val, _values)
 AST::Not.new val.last 
end

def _reduce_9(val, _values)
 AST::And.new val.first, val.last 
end

def _reduce_10(val, _values)
 AST::Or.new val.first, val.last 
end

def _reduce_11(val, _values)
 AST::Group.new val[1] 
end

# reduce 12 omitted

# reduce 13 omitted

def _reduce_14(val, _values)
 AST::IntegerEqual.new val.first, val.last 
end

def _reduce_15(val, _values)
 AST::IntegerGreaterThan.new val.first, val.last 
end

def _reduce_16(val, _values)
 AST::IntegerLessThan.new val.first, val.last 
end

def _reduce_17(val, _values)
 AST::IntegerBetween.new val.first, val[2], val.last 
end

def _reduce_18(val, _values)
 AST::IntegerIn.new val.first, val.last 
end

def _reduce_19(val, _values)
 AST::IntegerNotIn.new val.first, val.last 
end

def _reduce_20(val, _values)
 AST::StringEqual.new val.first, val.last 
end

def _reduce_21(val, _values)
 AST::StringGreaterThan.new val.first, val.last 
end

def _reduce_22(val, _values)
 AST::StringLessThan.new val.first, val.last 
end

def _reduce_23(val, _values)
 AST::StringIn.new val.first, val.last 
end

def _reduce_24(val, _values)
 AST::StringNotIn.new val.first, val.last 
end

def _reduce_25(val, _values)
 AST::IntegerArray.new val[1] 
end

# reduce 26 omitted

def _reduce_27(val, _values)
 [val.first, val.last].flatten 
end

def _reduce_28(val, _values)
 AST::StringArray.new val[1] 
end

# reduce 29 omitted

def _reduce_30(val, _values)
 [val.first, val.last].flatten 
end

def _reduce_31(val, _values)
 AST::Integer.new val.first.to_i 
end

def _reduce_32(val, _values)
 AST::String.new val.first 
end

def _reduce_33(val, _values)
 AST::Variable.new val.first 
end

def _reduce_34(val, _values)
 AST::Variable.new [val.first, val.last].flatten.join(".") 
end

def _reduce_none(val, _values)
  val[0]
end

  end   # class Parser
  end   # module Predicator
