#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'
module Predicator
  class GeneratedParser < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
     9,    31,    32,     7,     8,    14,    15,    16,    17,    18,
     9,    43,     6,     7,     8,    14,    15,    16,    17,    18,
     9,    44,     6,     7,     8,    14,    15,    16,    17,    18,
     9,   nil,     6,     7,     8,    14,    15,    16,    17,    18,
     9,   nil,     6,     7,     8,    14,    15,    16,    17,    18,
    20,    21,     6,    19,   nil,   nil,    20,    21,   nil,    22,
   nil,   nil,    42,    23,    28,    27,    26,    25,    24,    14,
    15,    16,    17,    18,    14,    15,    16,    17,    18,    14,
    15,    16,    17,    18,    14,    15,    16,    17,    18,    14,
    15,    16,    17,    18,    14,    15,    16,    17,    18,    14,
    15,    16,    17,    18,    14,    15,    16,    17,    18 ]

racc_action_check = [
     0,    18,    19,     0,     0,     0,     0,     0,     0,     0,
     6,    31,     0,     6,     6,     6,     6,     6,     6,     6,
     9,    35,     6,     9,     9,     9,     9,     9,     9,     9,
    20,   nil,     9,    20,    20,    20,    20,    20,    20,    20,
    21,   nil,    20,    21,    21,    21,    21,    21,    21,    21,
    29,    29,    21,     1,   nil,   nil,     1,     1,   nil,     5,
   nil,   nil,    29,     5,     5,     5,     5,     5,     5,    22,
    22,    22,    22,    22,    23,    23,    23,    23,    23,    24,
    24,    24,    24,    24,    25,    25,    25,    25,    25,    26,
    26,    26,    26,    26,    27,    27,    27,    27,    27,    28,
    28,    28,    28,    28,    44,    44,    44,    44,    44 ]

racc_action_pointer = [
    -2,    53,   nil,   nil,   nil,    47,     8,   nil,   nil,    18,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   -12,     2,
    28,    38,    62,    67,    72,    77,    82,    87,    92,    47,
   nil,     0,   nil,   nil,   nil,    18,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    97,   nil ]

racc_action_default = [
   -26,   -26,    -1,    -2,    -3,   -26,   -26,   -12,   -13,   -26,
   -17,   -18,   -19,   -20,   -21,   -22,   -23,   -24,   -26,   -26,
   -26,   -26,   -26,   -26,   -26,   -26,   -26,   -26,   -26,   -26,
   -16,   -26,    46,   -14,   -15,   -26,    -6,    -7,    -8,    -9,
   -10,   -11,    -5,   -25,   -26,    -4 ]

racc_goto_table = [
    35,    36,    37,    38,    39,    40,    41,     1,   nil,   nil,
   nil,   nil,   nil,    29,   nil,   nil,    30,   nil,   nil,   nil,
   nil,   nil,    45,   nil,   nil,   nil,   nil,    33,    34 ]

racc_goto_check = [
     5,     5,     5,     5,     5,     5,     5,     1,   nil,   nil,
   nil,   nil,   nil,     1,   nil,   nil,     1,   nil,   nil,   nil,
   nil,   nil,     5,   nil,   nil,   nil,   nil,     1,     1 ]

racc_goto_pointer = [
   nil,     7,   nil,   nil,   nil,   -22,   nil,   nil,   nil,   nil ]

racc_goto_default = [
   nil,   nil,     2,     3,     4,     5,    10,    11,    12,    13 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 23, :_reduce_none,
  1, 23, :_reduce_none,
  1, 23, :_reduce_none,
  5, 23, :_reduce_4,
  3, 23, :_reduce_none,
  3, 24, :_reduce_6,
  3, 24, :_reduce_7,
  3, 24, :_reduce_8,
  3, 24, :_reduce_9,
  3, 24, :_reduce_10,
  3, 24, :_reduce_11,
  1, 25, :_reduce_12,
  1, 25, :_reduce_13,
  3, 26, :_reduce_14,
  3, 26, :_reduce_15,
  2, 26, :_reduce_16,
  1, 27, :_reduce_none,
  1, 27, :_reduce_none,
  1, 28, :_reduce_none,
  1, 28, :_reduce_none,
  1, 30, :_reduce_21,
  1, 31, :_reduce_22,
  1, 31, :_reduce_23,
  1, 31, :_reduce_24,
  3, 29, :_reduce_25 ]

racc_reduce_n = 26

racc_shift_n = 46

racc_token_table = {
  false => 0,
  :error => 1,
  :tBANG => 2,
  :tAND => 3,
  :tOR => 4,
  :tTRUE => 5,
  :tFALSE => 6,
  :tSTRING => 7,
  :tFLOAT => 8,
  :tINTEGER => 9,
  :tDATE => 10,
  :tIDENTIFIER => 11,
  :tBETWEEN => 12,
  :tDOT => 13,
  :tLPAREN => 14,
  :tRPAREN => 15,
  :tEQ => 16,
  :tNEQ => 17,
  :tLEQ => 18,
  :tGEQ => 19,
  :tLT => 20,
  :tGT => 21 }

racc_nt_base = 22

racc_use_result_var = false

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "tBANG",
  "tAND",
  "tOR",
  "tTRUE",
  "tFALSE",
  "tSTRING",
  "tFLOAT",
  "tINTEGER",
  "tDATE",
  "tIDENTIFIER",
  "tBETWEEN",
  "tDOT",
  "tLPAREN",
  "tRPAREN",
  "tEQ",
  "tNEQ",
  "tLEQ",
  "tGEQ",
  "tLT",
  "tGT",
  "$start",
  "predicate",
  "relation_predicate",
  "boolean_predicate",
  "logical_predicate",
  "value",
  "scalar",
  "variable",
  "string",
  "literal" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

module_eval(<<'.,.,', 'parser.y', 13)
  def _reduce_4(val, _values)
     Predicator::Predicates::Between.new val[0], val[2], val[4] 
  end
.,.,

# reduce 5 omitted

module_eval(<<'.,.,', 'parser.y', 17)
  def _reduce_6(val, _values)
     Predicator::Predicates::Equal.new val[0], val[2] 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 18)
  def _reduce_7(val, _values)
     Predicator::Predicates::GreaterThan.new val[0], val[2] 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 19)
  def _reduce_8(val, _values)
     Predicator::Predicates::LessThan.new val[0], val[2] 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 20)
  def _reduce_9(val, _values)
     Predicator::Predicates::GreaterThanOrEqual.new val[0], val[2] 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 21)
  def _reduce_10(val, _values)
     Predicator::Predicates::LessThanOrEqual.new val[0], val[2] 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 22)
  def _reduce_11(val, _values)
     Predicator::Predicates::NotEqual.new val[0], val[2] 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 25)
  def _reduce_12(val, _values)
     Predicator::Predicates::True.new 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 26)
  def _reduce_13(val, _values)
     Predicator::Predicates::False.new 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 29)
  def _reduce_14(val, _values)
     Predicator::Predicates::And.new [val[0], val[2]] 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 30)
  def _reduce_15(val, _values)
     Predicator::Predicates::Or.new [val[0], val[2]] 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 31)
  def _reduce_16(val, _values)
     Predicator::Predicates::Not.new val[0] 
  end
.,.,

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

module_eval(<<'.,.,', 'parser.y', 42)
  def _reduce_21(val, _values)
     val[0] 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 45)
  def _reduce_22(val, _values)
     val[0].to_f 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 46)
  def _reduce_23(val, _values)
     val[0].to_i 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 47)
  def _reduce_24(val, _values)
     Date.new *val[0] 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 50)
  def _reduce_25(val, _values)
     Predicator::Variable.new val[0], val[2] 
  end
.,.,

def _reduce_none(val, _values)
  val[0]
end

  end   # class GeneratedParser
  end   # module Predicator
