#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'

require "predicator/lexer.rex"
require "predicator/visitors"
require "predicator/ast"
module Predicator
  class Parser < Racc::Parser

    def initialize
      @lexer = Lexer.new
    end

    def parse string
      @lexer.parse string
      do_parse
    end

    def next_token
      @lexer.next_token
    end

    def on_error type, val, values
      super
    rescue Racc::ParseError
      trace = values.each_with_index.map{|l, i| "#{' ' * i}#{l}"}
      raise ParseError, "\nparse error on value #{val.inspect}\n#{trace.join("\n")}"
    end

##### State transition tables begin ###

racc_action_table = [
     6,     7,    10,     6,     7,    10,     9,    15,    29,     9,
     6,     7,    10,     6,     7,    10,     9,    16,    17,     9,
    16,    17,    14,    16,    17,    14,    57,     6,     7,    10,
    25,    26,    14,     9,    35,    14,    20,    21,    22,    23,
    24,    18,    19,    53,    35,    36,    68,    37,    39,    14,
    69,    16,    17,    35,    36,    35,    37,    39,    37,    39,
    66,    50,    35,    36,    67,    37,    39,    16,    17,    54,
    55,    35,    36,    37,    39,    35,    52,    51,    36,    50,
    56 ]

racc_action_check = [
     0,     0,     0,     9,     9,     9,     0,     1,    15,     9,
    10,    10,    10,    16,    16,    16,    10,    27,    27,    16,
     1,     1,     0,    30,    30,     9,    47,    17,    17,    17,
     8,     8,    10,    17,    67,    16,     8,     8,     8,     8,
     8,     8,     8,    28,    21,    21,    60,    21,    21,    17,
    60,    28,    28,    22,    22,    23,    22,    22,    23,    23,
    58,    51,    20,    20,    58,    20,    20,    31,    31,    38,
    38,    50,    50,    57,    57,    56,    26,    25,    69,    24,
    46 ]

racc_action_pointer = [
    -2,     7,   nil,   nil,   nil,   nil,   nil,   nil,    21,     1,
     8,   nil,   nil,   nil,   nil,     8,    11,    25,   nil,   nil,
    40,    22,    31,    33,    73,    58,    52,     4,    38,   nil,
    10,    54,   nil,   nil,   nil,   nil,   nil,   nil,    42,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    67,    13,   nil,   nil,
    49,    55,   nil,   nil,   nil,   nil,    53,    48,    53,   nil,
    39,   nil,   nil,   nil,   nil,   nil,   nil,    12,   nil,    55,
   nil,   nil ]

racc_action_default = [
   -46,   -46,    -1,    -2,    -3,    -4,    -5,    -6,    -7,   -46,
   -46,   -14,   -15,   -16,   -44,   -46,   -46,   -46,   -11,   -12,
   -46,   -46,   -46,   -46,   -46,   -46,   -46,    -8,   -46,    72,
    -9,   -10,   -17,   -23,   -28,   -38,   -39,   -40,   -46,   -43,
   -18,   -24,   -29,   -19,   -25,   -30,   -46,   -46,   -21,   -26,
   -46,   -46,   -45,   -13,   -41,   -42,   -46,   -46,   -46,   -33,
   -46,   -36,   -22,   -27,   -20,   -31,   -32,   -46,   -35,   -46,
   -34,   -37 ]

racc_goto_table = [
    33,    41,    44,    32,    40,    43,    46,    34,    42,    45,
    47,    48,     1,    49,    58,    60,   nil,   nil,   nil,   nil,
   nil,    27,    28,   nil,   nil,   nil,   nil,   nil,    30,    31,
    61,   nil,   nil,    59,   nil,   nil,   nil,   nil,    62,    64,
    63,   nil,   nil,   nil,    65,   nil,   nil,   nil,   nil,    71,
    70 ]

racc_goto_check = [
    12,    12,    12,    10,    10,    10,    10,    14,    14,    14,
    14,    11,     1,    13,    15,    16,   nil,   nil,   nil,   nil,
   nil,     1,     1,   nil,   nil,   nil,   nil,   nil,     1,     1,
    12,   nil,   nil,    10,   nil,   nil,   nil,   nil,    11,    10,
    13,   nil,   nil,   nil,    14,   nil,   nil,   nil,   nil,    12,
    10 ]

racc_goto_pointer = [
   nil,    12,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   -17,   -13,   -20,   -11,   -13,   -36,   -35,   nil ]

racc_goto_default = [
   nil,   nil,     2,     3,     4,     5,     8,    11,    12,    13,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    38 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 30, :_reduce_none,
  1, 30, :_reduce_none,
  1, 30, :_reduce_none,
  1, 30, :_reduce_none,
  1, 31, :_reduce_5,
  1, 31, :_reduce_6,
  1, 31, :_reduce_7,
  2, 32, :_reduce_8,
  3, 32, :_reduce_9,
  3, 32, :_reduce_10,
  2, 32, :_reduce_11,
  2, 32, :_reduce_12,
  3, 33, :_reduce_13,
  1, 34, :_reduce_none,
  1, 34, :_reduce_none,
  1, 34, :_reduce_none,
  3, 36, :_reduce_17,
  3, 36, :_reduce_18,
  3, 36, :_reduce_19,
  5, 36, :_reduce_20,
  3, 36, :_reduce_21,
  4, 36, :_reduce_22,
  3, 37, :_reduce_23,
  3, 37, :_reduce_24,
  3, 37, :_reduce_25,
  3, 37, :_reduce_26,
  4, 37, :_reduce_27,
  3, 38, :_reduce_28,
  3, 38, :_reduce_29,
  3, 38, :_reduce_30,
  5, 38, :_reduce_31,
  3, 40, :_reduce_32,
  1, 44, :_reduce_none,
  3, 44, :_reduce_34,
  3, 42, :_reduce_35,
  1, 45, :_reduce_none,
  3, 45, :_reduce_37,
  1, 39, :_reduce_38,
  1, 41, :_reduce_39,
  1, 43, :_reduce_40,
  2, 43, :_reduce_41,
  2, 43, :_reduce_42,
  1, 46, :_reduce_43,
  1, 35, :_reduce_44,
  3, 35, :_reduce_45 ]

racc_reduce_n = 46

racc_shift_n = 72

racc_token_table = {
  false => 0,
  :error => 1,
  :TRUE => 2,
  :FALSE => 3,
  :LPAREN => 4,
  :RPAREN => 5,
  :LBRACKET => 6,
  :RBRACKET => 7,
  :BANG => 8,
  :NOT => 9,
  :DOT => 10,
  :COMMA => 11,
  :AT => 12,
  :AND => 13,
  :OR => 14,
  :EQ => 15,
  :GT => 16,
  :LT => 17,
  :BETWEEN => 18,
  :IN => 19,
  :PRESENT => 20,
  :BLANK => 21,
  :INTEGER => 22,
  :STRING => 23,
  :IDENTIFIER => 24,
  :DATE => 25,
  :DURATION => 26,
  :AGO => 27,
  :FROMNOW => 28 }

racc_nt_base = 29

racc_use_result_var = false

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "TRUE",
  "FALSE",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "BANG",
  "NOT",
  "DOT",
  "COMMA",
  "AT",
  "AND",
  "OR",
  "EQ",
  "GT",
  "LT",
  "BETWEEN",
  "IN",
  "PRESENT",
  "BLANK",
  "INTEGER",
  "STRING",
  "IDENTIFIER",
  "DATE",
  "DURATION",
  "AGO",
  "FROMNOW",
  "$start",
  "predicate",
  "boolean_predicate",
  "logical_predicate",
  "group_predicate",
  "comparison_predicate",
  "variable",
  "integer_comparison_predicate",
  "string_comparison_predicate",
  "date_comparison_predicate",
  "integer",
  "integer_array",
  "string",
  "string_array",
  "date",
  "integer_array_contents",
  "string_array_contents",
  "duration" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

def _reduce_5(val, _values)
 AST::True.new true 
end

def _reduce_6(val, _values)
 AST::False.new false 
end

def _reduce_7(val, _values)
 AST::BooleanVariable.new val.first 
end

def _reduce_8(val, _values)
 AST::Not.new val.last 
end

def _reduce_9(val, _values)
 AST::And.new val.first, val.last 
end

def _reduce_10(val, _values)
 AST::Or.new val.first, val.last 
end

def _reduce_11(val, _values)
 AST::Present.new val.first 
end

def _reduce_12(val, _values)
 AST::Blank.new val.first 
end

def _reduce_13(val, _values)
 AST::Group.new val[1] 
end

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

def _reduce_17(val, _values)
 AST::IntegerEqual.new val.first, val.last 
end

def _reduce_18(val, _values)
 AST::IntegerGreaterThan.new val.first, val.last 
end

def _reduce_19(val, _values)
 AST::IntegerLessThan.new val.first, val.last 
end

def _reduce_20(val, _values)
 AST::IntegerBetween.new val.first, val[2], val.last 
end

def _reduce_21(val, _values)
 AST::IntegerIn.new val.first, val.last 
end

def _reduce_22(val, _values)
 AST::IntegerNotIn.new val.first, val.last 
end

def _reduce_23(val, _values)
 AST::StringEqual.new val.first, val.last 
end

def _reduce_24(val, _values)
 AST::StringGreaterThan.new val.first, val.last 
end

def _reduce_25(val, _values)
 AST::StringLessThan.new val.first, val.last 
end

def _reduce_26(val, _values)
 AST::StringIn.new val.first, val.last 
end

def _reduce_27(val, _values)
 AST::StringNotIn.new val.first, val.last 
end

def _reduce_28(val, _values)
 AST::DateEqual.new val.first, val.last 
end

def _reduce_29(val, _values)
 AST::DateGreaterThan.new val.first, val.last 
end

def _reduce_30(val, _values)
 AST::DateLessThan.new val.first, val.last 
end

def _reduce_31(val, _values)
 AST::DateBetween.new val.first, val[2], val.last 
end

def _reduce_32(val, _values)
 AST::IntegerArray.new val[1] 
end

# reduce 33 omitted

def _reduce_34(val, _values)
 [val.first, val.last].flatten 
end

def _reduce_35(val, _values)
 AST::StringArray.new val[1] 
end

# reduce 36 omitted

def _reduce_37(val, _values)
 [val.first, val.last].flatten 
end

def _reduce_38(val, _values)
 AST::Integer.new val.first.to_i 
end

def _reduce_39(val, _values)
 AST::String.new val.first 
end

def _reduce_40(val, _values)
 AST::Date.new val.first 
end

def _reduce_41(val, _values)
 AST::DateAgo.new val.first 
end

def _reduce_42(val, _values)
 AST::DateFromNow.new val.first 
end

def _reduce_43(val, _values)
 AST::Duration.new val.first 
end

def _reduce_44(val, _values)
 AST::Variable.new val.first 
end

def _reduce_45(val, _values)
 AST::Variable.new [val.first, val.last].flatten.join(".") 
end

def _reduce_none(val, _values)
  val[0]
end

  end   # class Parser
  end   # module Predicator
