#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'

require "predicator/lexer.rex"
require "predicator/visitors"
require "predicator/ast"
module Predicator
  class Parser < Racc::Parser

    def initialize
      @lexer = Lexer.new
    end

    def parse string
      @lexer.parse string
      do_parse
    end

    def next_token
      @lexer.next_token
    end

    def on_error type, val, values
      super
    rescue Racc::ParseError
      trace = values.each_with_index.map{|l, i| "#{' ' * i}#{l}"}
      raise ParseError, "\nparse error on value #{val.inspect}\n#{trace.join("\n")}"
    end

##### State transition tables begin ###

racc_action_table = [
     6,     7,    10,     6,     7,    10,     9,    15,    31,     9,
     6,     7,    10,     6,     7,    10,     9,    16,    17,     9,
    16,    17,    14,    16,    17,    14,    52,     6,     7,    10,
    25,    28,    14,     9,    53,    14,    20,    21,    22,    23,
    24,    18,    19,    37,    57,    38,    39,    41,    38,    14,
    26,    27,    16,    17,    37,    38,    56,    39,    41,    37,
    38,    60,    39,    41,    37,    38,    70,    39,    41,    72,
    71,    16,    17,    73,    58,    59,    37,    38,    39,    41,
    61,    52,    37,    37,    38 ]

racc_action_check = [
     0,     0,     0,     9,     9,     9,     0,     1,    15,     9,
    10,    10,    10,    16,    16,    16,    10,    29,    29,    16,
     1,     1,     0,    32,    32,     9,    24,    17,    17,    17,
     8,     8,    10,    17,    25,    16,     8,     8,     8,     8,
     8,     8,     8,    23,    30,    26,    23,    23,    27,    17,
     8,     8,    30,    30,    20,    20,    28,    20,    20,    21,
    21,    48,    21,    21,    22,    22,    62,    22,    22,    64,
    62,    33,    33,    64,    40,    40,    52,    52,    61,    61,
    49,    53,    60,    71,    73 ]

racc_action_pointer = [
    -2,     7,   nil,   nil,   nil,   nil,   nil,   nil,    21,     1,
     8,   nil,   nil,   nil,   nil,     8,    11,    25,   nil,   nil,
    32,    37,    42,    21,    20,    15,    22,    25,    32,     4,
    39,   nil,    10,    58,   nil,   nil,   nil,   nil,   nil,   nil,
    47,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    48,    67,
   nil,   nil,    54,    75,   nil,   nil,   nil,   nil,   nil,   nil,
    60,    53,    59,   nil,    62,   nil,   nil,   nil,   nil,   nil,
   nil,    61,   nil,    61,   nil,   nil ]

racc_action_default = [
   -48,   -48,    -1,    -2,    -3,    -4,    -5,    -6,    -7,   -48,
   -48,   -14,   -15,   -16,   -46,   -48,   -48,   -48,   -11,   -12,
   -48,   -48,   -48,   -48,   -48,   -48,   -48,   -48,   -48,    -8,
   -48,    76,    -9,   -10,   -17,   -23,   -30,   -40,   -41,   -42,
   -48,   -45,   -18,   -24,   -31,   -19,   -25,   -32,   -48,   -48,
   -21,   -26,   -48,   -48,   -28,   -29,   -47,   -13,   -43,   -44,
   -48,   -48,   -48,   -35,   -48,   -38,   -22,   -27,   -20,   -33,
   -34,   -48,   -37,   -48,   -36,   -39 ]

racc_goto_table = [
    35,    43,    46,    62,    50,    51,    54,    55,    34,    42,
    45,    48,     1,    36,    44,    47,    49,    64,   nil,   nil,
   nil,    29,    30,   nil,   nil,   nil,   nil,   nil,    32,    33,
   nil,   nil,    65,    66,    67,   nil,   nil,   nil,   nil,   nil,
    63,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    68,   nil,
   nil,   nil,   nil,    75,    69,   nil,   nil,   nil,   nil,    74 ]

racc_goto_check = [
    12,    12,    12,    15,    11,    13,    12,    12,    10,    10,
    10,    10,     1,    14,    14,    14,    14,    16,   nil,   nil,
   nil,     1,     1,   nil,   nil,   nil,   nil,   nil,     1,     1,
   nil,   nil,    12,    11,    13,   nil,   nil,   nil,   nil,   nil,
    10,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    10,   nil,
   nil,   nil,   nil,    12,    14,   nil,   nil,   nil,   nil,    10 ]

racc_goto_pointer = [
   nil,    12,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   -12,   -20,   -20,   -19,    -7,   -49,   -35,   nil ]

racc_goto_default = [
   nil,   nil,     2,     3,     4,     5,     8,    11,    12,    13,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    40 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 32, :_reduce_none,
  1, 32, :_reduce_none,
  1, 32, :_reduce_none,
  1, 32, :_reduce_none,
  1, 33, :_reduce_5,
  1, 33, :_reduce_6,
  1, 33, :_reduce_7,
  2, 34, :_reduce_8,
  3, 34, :_reduce_9,
  3, 34, :_reduce_10,
  2, 34, :_reduce_11,
  2, 34, :_reduce_12,
  3, 35, :_reduce_13,
  1, 36, :_reduce_none,
  1, 36, :_reduce_none,
  1, 36, :_reduce_none,
  3, 38, :_reduce_17,
  3, 38, :_reduce_18,
  3, 38, :_reduce_19,
  5, 38, :_reduce_20,
  3, 38, :_reduce_21,
  4, 38, :_reduce_22,
  3, 39, :_reduce_23,
  3, 39, :_reduce_24,
  3, 39, :_reduce_25,
  3, 39, :_reduce_26,
  4, 39, :_reduce_27,
  3, 39, :_reduce_28,
  3, 39, :_reduce_29,
  3, 40, :_reduce_30,
  3, 40, :_reduce_31,
  3, 40, :_reduce_32,
  5, 40, :_reduce_33,
  3, 42, :_reduce_34,
  1, 46, :_reduce_none,
  3, 46, :_reduce_36,
  3, 44, :_reduce_37,
  1, 47, :_reduce_none,
  3, 47, :_reduce_39,
  1, 41, :_reduce_40,
  1, 43, :_reduce_41,
  1, 45, :_reduce_42,
  2, 45, :_reduce_43,
  2, 45, :_reduce_44,
  1, 48, :_reduce_45,
  1, 37, :_reduce_46,
  3, 37, :_reduce_47 ]

racc_reduce_n = 48

racc_shift_n = 76

racc_token_table = {
  false => 0,
  :error => 1,
  :TRUE => 2,
  :FALSE => 3,
  :LPAREN => 4,
  :RPAREN => 5,
  :LBRACKET => 6,
  :RBRACKET => 7,
  :BANG => 8,
  :NOT => 9,
  :DOT => 10,
  :COMMA => 11,
  :AT => 12,
  :AND => 13,
  :OR => 14,
  :EQ => 15,
  :GT => 16,
  :LT => 17,
  :BETWEEN => 18,
  :IN => 19,
  :PRESENT => 20,
  :BLANK => 21,
  :INTEGER => 22,
  :STRING => 23,
  :IDENTIFIER => 24,
  :DATE => 25,
  :DURATION => 26,
  :AGO => 27,
  :FROMNOW => 28,
  :STARTSWITH => 29,
  :ENDSWITH => 30 }

racc_nt_base = 31

racc_use_result_var = false

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "TRUE",
  "FALSE",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "BANG",
  "NOT",
  "DOT",
  "COMMA",
  "AT",
  "AND",
  "OR",
  "EQ",
  "GT",
  "LT",
  "BETWEEN",
  "IN",
  "PRESENT",
  "BLANK",
  "INTEGER",
  "STRING",
  "IDENTIFIER",
  "DATE",
  "DURATION",
  "AGO",
  "FROMNOW",
  "STARTSWITH",
  "ENDSWITH",
  "$start",
  "predicate",
  "boolean_predicate",
  "logical_predicate",
  "group_predicate",
  "comparison_predicate",
  "variable",
  "integer_comparison_predicate",
  "string_comparison_predicate",
  "date_comparison_predicate",
  "integer",
  "integer_array",
  "string",
  "string_array",
  "date",
  "integer_array_contents",
  "string_array_contents",
  "duration" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

def _reduce_5(val, _values)
 AST::True.new true 
end

def _reduce_6(val, _values)
 AST::False.new false 
end

def _reduce_7(val, _values)
 AST::BooleanVariable.new val.first 
end

def _reduce_8(val, _values)
 AST::Not.new val.last 
end

def _reduce_9(val, _values)
 AST::And.new val.first, val.last 
end

def _reduce_10(val, _values)
 AST::Or.new val.first, val.last 
end

def _reduce_11(val, _values)
 AST::Present.new val.first 
end

def _reduce_12(val, _values)
 AST::Blank.new val.first 
end

def _reduce_13(val, _values)
 AST::Group.new val[1] 
end

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

def _reduce_17(val, _values)
 AST::IntegerEqual.new val.first, val.last 
end

def _reduce_18(val, _values)
 AST::IntegerGreaterThan.new val.first, val.last 
end

def _reduce_19(val, _values)
 AST::IntegerLessThan.new val.first, val.last 
end

def _reduce_20(val, _values)
 AST::IntegerBetween.new val.first, val[2], val.last 
end

def _reduce_21(val, _values)
 AST::IntegerIn.new val.first, val.last 
end

def _reduce_22(val, _values)
 AST::IntegerNotIn.new val.first, val.last 
end

def _reduce_23(val, _values)
 AST::StringEqual.new val.first, val.last 
end

def _reduce_24(val, _values)
 AST::StringGreaterThan.new val.first, val.last 
end

def _reduce_25(val, _values)
 AST::StringLessThan.new val.first, val.last 
end

def _reduce_26(val, _values)
 AST::StringIn.new val.first, val.last 
end

def _reduce_27(val, _values)
 AST::StringNotIn.new val.first, val.last 
end

def _reduce_28(val, _values)
 AST::StringStartsWith.new val.first, val.last 
end

def _reduce_29(val, _values)
 AST::StringEndsWith.new val.first, val.last 
end

def _reduce_30(val, _values)
 AST::DateEqual.new val.first, val.last 
end

def _reduce_31(val, _values)
 AST::DateGreaterThan.new val.first, val.last 
end

def _reduce_32(val, _values)
 AST::DateLessThan.new val.first, val.last 
end

def _reduce_33(val, _values)
 AST::DateBetween.new val.first, val[2], val.last 
end

def _reduce_34(val, _values)
 AST::IntegerArray.new val[1] 
end

# reduce 35 omitted

def _reduce_36(val, _values)
 [val.first, val.last].flatten 
end

def _reduce_37(val, _values)
 AST::StringArray.new val[1] 
end

# reduce 38 omitted

def _reduce_39(val, _values)
 [val.first, val.last].flatten 
end

def _reduce_40(val, _values)
 AST::Integer.new val.first.to_i 
end

def _reduce_41(val, _values)
 AST::String.new val.first 
end

def _reduce_42(val, _values)
 AST::Date.new val.first 
end

def _reduce_43(val, _values)
 AST::DateAgo.new val.first 
end

def _reduce_44(val, _values)
 AST::DateFromNow.new val.first 
end

def _reduce_45(val, _values)
 AST::Duration.new val.first 
end

def _reduce_46(val, _values)
 AST::Variable.new val.first 
end

def _reduce_47(val, _values)
 AST::Variable.new [val.first, val.last].flatten.join(".") 
end

def _reduce_none(val, _values)
  val[0]
end

  end   # class Parser
  end   # module Predicator
