
	package predicator

	import (
		"testing"
	)

	// Test_int_eq_int -- AUTOGENERATED DO NOT EDIT
	func Test_int_eq_int(t *testing.T) {
		instructions := [][]interface {}{[]interface {}{"lit", 1}, []interface {}{"lit", 1}, []interface {}{"compare", "EQ"}}
		tt := []struct{
			Name string
			Result bool
			Data   map[string]interface{} 
		}{
		
			{
				"with_no_context",
				true,
				map[string]interface {}(nil),
			},
		
		}
		for _, test := range tt {
			e := NewEvaluator(instructions, test.Data)
			got := e.result()
			if  got != test.Result {
				t.Logf("FAILED %s_%s expected %v got %v", "int_eq_int", test.Name, test.Result, got)
				t.Fail()
			}
			if e.stack.count > 0 {
				t.Logf("FAILED %s_%s expected empty stack",  "int_eq_int", test.Name)
				t.Fail()
			}
		}
	}
	