
	package predicator

	import (
		"testing"
	)

	// Test_variable_eq_date -- AUTOGENERATED DO NOT EDIT
	func Test_variable_eq_date(t *testing.T) {
		instructions := [][]interface {}{[]interface {}{"load", "start_date"}, []interface {}{"to_date"}, []interface {}{"lit", "2017-09-10"}, []interface {}{"compare", "EQ"}}
		tt := []struct{
			Name string
			Result bool
			Data   map[string]interface{} 
		}{
		
			{
				"with_no_context",
				false,
				map[string]interface {}(nil),
			},
		
			{
				"with_blank_string",
				false,
				map[string]interface {}{"age":""},
			},
		
			{
				"with_correct_date_string",
				true,
				map[string]interface {}{"start_date":"2017-09-10"},
			},
		
			{
				"with_incorrect_date_string",
				false,
				map[string]interface {}{"start_date":"2017-09-09"},
			},
		
		}
		for _, test := range tt {
			e := NewEvaluator(instructions, test.Data)
			got := e.result()
			if  got != test.Result {
				t.Logf("FAILED %s_%s expected %v got %v", "variable_eq_date", test.Name, test.Result, got)
				t.Fail()
			}
			if e.stack.count > 0 {
				t.Logf("FAILED %s_%s expected empty stack",  "variable_eq_date", test.Name)
				t.Fail()
			}
		}
	}
	