
	package predicator

	import (
		"testing"
	)

	// Test_variable_lt_duration_from_now -- AUTOGENERATED DO NOT EDIT
	func Test_variable_lt_duration_from_now(t *testing.T) {
		instructions := [][]interface {}{[]interface {}{"load", "plan_end_date"}, []interface {}{"to_date"}, []interface {}{"lit", 259200}, []interface {}{"date_from_now"}, []interface {}{"compare", "LT"}}
		tt := []struct{
			Name string
			Result bool
			Data   map[string]interface{} 
		}{
		
			{
				"with_no_context",
				false,
				map[string]interface {}(nil),
			},
		
			{
				"with_blank_date",
				false,
				map[string]interface {}{"plan_end_date":""},
			},
		
			{
				"with_future_date",
				false,
				map[string]interface {}{"plan_end_date":"2299-01-01"},
			},
		
			{
				"with_past_date",
				true,
				map[string]interface {}{"plan_end_date":"1999-01-01"},
			},
		
		}
		for _, test := range tt {
			e := NewEvaluator(instructions, test.Data)
			got := e.result()
			if  got != test.Result {
				t.Logf("FAILED %s_%s expected %v got %v", "variable_lt_duration_from_now", test.Name, test.Result, got)
				t.Fail()
			}
			if e.stack.count > 0 {
				t.Logf("FAILED %s_%s expected empty stack",  "variable_lt_duration_from_now", test.Name)
				t.Fail()
			}
		}
	}
	